name: untitled
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.20.2
  flutter_slidable: ^4.0.3
  table_calendar: ^3.1.2
  image_picker: ^1.2.2
  fluttertoast: ^9.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img2.jpeg
    - assets/img3.jpeg
    - assets/img5.jpeg
    - assets/img6.jpeg
    - assets/img7.jpeg
    - assets/img8.jpeg
    - assets/OIP (5).jpeg

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700